# server
server:
  port: 8086
  servlet:
    context-path:

# spring
spring:
  ## 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  ## 彩色日志
  output:
    ansi:
      enabled: always
  ## jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ## thymeleaf
  thymeleaf:
    cache: false

# logging
logging:
  level:
    org.springframework.security: info






